### ISSUE TITLE
Background monitor will stop running when _get_all_bare causes an exception.

### ISSUE THREAD

**Issue by mikelawrence** [TomFaulkner/SenseMe#25]
There needs to be a try/except block around code in _get_all_bare() or _loop() in background_monitor. A good example of this is to simply cut the power to the fan and a "Host not reachable" exception should occur.

**Comment by TomFaulkner** [comment]
Hadn't thought about network disconnects. This does need to be fixed. I don't turn my fan off, but I would imagine many do, along with all of the other random wifi related issues that could occur.

**Comment by TomFaulkner** [comment]
Merged, and 0.1.2 has been uploaded to PyPI. Let me know how it works for you!
